// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlT7rb7J8SE-GgcRT247XaHz0_4fA9SVo',
    appId: '1:680421664041:web:d1fbc03b5a099873fc8338',
    messagingSenderId: '680421664041',
    projectId: 'notes-app-jhuma',
    authDomain: 'notes-app-jhuma.firebaseapp.com',
    storageBucket: 'notes-app-jhuma.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaZOwpHsqBEadX6-ViRiPMtfOpQJ57IMQ',
    appId: '1:680421664041:android:198fb6d53539db29fc8338',
    messagingSenderId: '680421664041',
    projectId: 'notes-app-jhuma',
    storageBucket: 'notes-app-jhuma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRuVvLpLe1ZLOvKz6fKNECwkpWhEG1oCE',
    appId: '1:680421664041:ios:0a442f29528a1ddbfc8338',
    messagingSenderId: '680421664041',
    projectId: 'notes-app-jhuma',
    storageBucket: 'notes-app-jhuma.firebasestorage.app',
    iosBundleId: 'com.example.notesManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRuVvLpLe1ZLOvKz6fKNECwkpWhEG1oCE',
    appId: '1:680421664041:ios:0a442f29528a1ddbfc8338',
    messagingSenderId: '680421664041',
    projectId: 'notes-app-jhuma',
    storageBucket: 'notes-app-jhuma.firebasestorage.app',
    iosBundleId: 'com.example.notesManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlT7rb7J8SE-GgcRT247XaHz0_4fA9SVo',
    appId: '1:680421664041:web:ad408717367fb73cfc8338',
    messagingSenderId: '680421664041',
    projectId: 'notes-app-jhuma',
    authDomain: 'notes-app-jhuma.firebaseapp.com',
    storageBucket: 'notes-app-jhuma.firebasestorage.app',
  );
}
